"""3

Revision ID: 1b68b48a026a
Revises: 9413a57a9a46
Create Date: 2024-01-05 16:43:53.520159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b68b48a026a'
down_revision: Union[str, None] = '9413a57a9a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_review', sa.Column('grade', sa.Integer(), nullable=False))
    op.drop_column('item_review', 'grade_overall')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_review', sa.Column('grade_overall', sa.INTEGER(), nullable=False))
    op.drop_column('item_review', 'grade')
    # ### end Alembic commands ###
