"""Sacond

Revision ID: 18da548b762e
Revises: da7bfa9015a7
Create Date: 2022-02-05 20:32:51.065741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18da548b762e'
down_revision = 'da7bfa9015a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablename_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('event_type'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tablename_stat_id'), 'tablename_stat', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tablename_stat_id'), table_name='tablename_stat')
    op.drop_table('tablename_stat')
    # ### end Alembic commands ###
