"""3

Revision ID: 3b2c97bb8775
Revises: 18da548b762e
Create Date: 2022-02-05 20:45:20.716758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2c97bb8775'
down_revision = '18da548b762e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tablename_stat_date_key', 'tablename_stat', type_='unique')
    op.drop_constraint('tablename_stat_event_id_key', 'tablename_stat', type_='unique')
    op.drop_constraint('tablename_stat_event_type_key', 'tablename_stat', type_='unique')
    op.drop_constraint('tablename_stat_user_id_key', 'tablename_stat', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tablename_stat_user_id_key', 'tablename_stat', ['user_id'])
    op.create_unique_constraint('tablename_stat_event_type_key', 'tablename_stat', ['event_type'])
    op.create_unique_constraint('tablename_stat_event_id_key', 'tablename_stat', ['event_id'])
    op.create_unique_constraint('tablename_stat_date_key', 'tablename_stat', ['date'])
    # ### end Alembic commands ###
