"""2

Revision ID: 98e7d1181fb3
Revises: 09567b478bc5
Create Date: 2022-02-07 18:01:53.348708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e7d1181fb3'
down_revision = '09567b478bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
